# Generated by Django 4.2.3 on 2023-08-21 05:06

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="TblAzs",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("geomtype", models.TextField(blank=True, null=True)),
                ("coordinates", models.TextField(blank=True, null=True)),
            ],
            options={
                "db_table": "tbl_azs",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="TblRoads",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("road_code", models.IntegerField(blank=True, null=True)),
                ("name", models.TextField(blank=True, null=True)),
                ("length_km", models.FloatField(blank=True, null=True)),
                ("geomtype", models.TextField(blank=True, null=True)),
                ("coordinates", models.TextField(blank=True, null=True)),
            ],
            options={
                "db_table": "tbl_roads",
                "managed": False,
            },
        ),
    ]
