# Generated by Django 4.2.4 on 2023-08-22 13:39

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("roads", "0002_alter_tblazs_table"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="tblazs",
            table="tbl_azs",
        ),
    ]
